queue_rules:
  - name: automerge
    queue_conditions:
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    merge_conditions:
      - check-success=python3.9-x64 windows-latest
      - check-success=python3.9-x64 ubuntu-latest
      - check-success=python3.9-x64 macOS-latest
      - check-success=python3.10-x64 windows-latest
      - check-success=python3.10-x64 ubuntu-latest
      - check-success=python3.10-x64 macOS-latest
      - check-success=python3.11-x64 windows-latest
      - check-success=python3.11-x64 ubuntu-latest
      - check-success=python3.11-x64 macOS-latest
      - check-success=Build, rustfmt, and python lint
      - check-success=Coverage
      - check-success=Build Docs
    merge_method: squash

pull_request_rules:
  - name: backport
    conditions:
      - label=stable-backport-potential
    actions:
      backport:
        branches:
          - stable/0.14
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
