queue_rules:
  - name: automerge
    conditions:
      - check-success=python3.7-x64 windows-latest
      - check-success=python3.7-x64 ubuntu-latest
      - check-success=python3.7-x64 macOS-latest
      - check-success=python3.8-x64 windows-latest
      - check-success=python3.8-x64 ubuntu-latest
      - check-success=python3.8-x64 macOS-latest
      - check-success=python3.9-x64 windows-latest
      - check-success=python3.9-x64 ubuntu-latest
      - check-success=python3.9-x64 macOS-latest
      - check-success=python3.10-x64 windows-latest
      - check-success=python3.10-x64 ubuntu-latest
      - check-success=python3.10-x64 macOS-latest
      - check-success=python3.11-x64 windows-latest
      - check-success=python3.11-x64 ubuntu-latest
      - check-success=python3.11-x64 macOS-latest
      - check-success=Build, rustfmt, and python lint
      - check-success=Coverage
      - check-success=Build Docs

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    actions:
      queue:
        name: automerge
        method: squash
  - name: backport
    conditions:
      - label=stable-backport-potential
    actions:
      backport:
        branches:
          - stable/0.13
