# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
  - epub
  - pdf

conda:
  environment: .conda-rtd-environment.yml

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
