# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This file contains only type annotations for PyO3 functions and classes
# For implementation details, see __init__.py and lib.rs

import retworkx_generators as generators
from .custom_return_types import *

from typing import Any, ClassVar

class DAGHasCycle(Exception): ...
class DAGWouldCycle(Exception): ...
class InvalidNode(Exception): ...
class NoEdgeBetweenNodes(Exception): ...
class NoPathFound(Exception): ...
class NoSuitableNeighbors(Exception): ...
class NullGraph(Exception): ...

class PyDiGraph:
    check_cycle: ClassVar[Any] = ...
    multigraph: ClassVar[Any] = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def add_child(self, *args, **kwargs) -> Any: ...
    def add_edge(self, *args, **kwargs) -> Any: ...
    def add_edges_from(self, *args, **kwargs) -> Any: ...
    def add_edges_from_no_data(self, *args, **kwargs) -> Any: ...
    def add_node(self, *args, **kwargs) -> Any: ...
    def add_nodes_from(self, *args, **kwargs) -> Any: ...
    def add_parent(self, *args, **kwargs) -> Any: ...
    def adj(self, *args, **kwargs) -> Any: ...
    def adj_direction(self, *args, **kwargs) -> Any: ...
    def compose(other_graph, node_map) -> Any: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def edge_index_map(self, *args, **kwargs) -> Any: ...
    def edge_indices(self, *args, **kwargs) -> Any: ...
    def edge_list(self, *args, **kwargs) -> Any: ...
    def edges(self, *args, **kwargs) -> Any: ...
    def extend_from_edge_list(self, *args, **kwargs) -> Any: ...
    def extend_from_weighted_edge_list(self, *args, **kwargs) -> Any: ...
    def find_adjacent_node_by_edge(self, *args, **kwargs) -> Any: ...
    def find_node_by_weight(self, *args, **kwargs) -> Any: ...
    def find_predecessors_by_edge(self, *args, **kwargs) -> Any: ...
    def find_successors_by_edge(self, *args, **kwargs) -> Any: ...
    def from_adjacency_matrix(self, *args, **kwargs) -> Any: ...
    def get_all_edge_data(self, *args, **kwargs) -> Any: ...
    def get_edge_data(self, *args, **kwargs) -> Any: ...
    def get_node_data(self, *args, **kwargs) -> Any: ...
    def has_edge(self, *args, **kwargs) -> Any: ...
    def in_degree(self, *args, **kwargs) -> Any: ...
    def in_edges(self, *args, **kwargs) -> Any: ...
    def insert_node_on_in_edges(self, *args, **kwargs) -> Any: ...
    def insert_node_on_in_edges_multiple(self, *args, **kwargs) -> Any: ...
    def insert_node_on_out_edges(self, *args, **kwargs) -> Any: ...
    def insert_node_on_out_edges_multiple(self, *args, **kwargs) -> Any: ...
    def is_symmetric(self, *args, **kwargs) -> Any: ...
    def merge_nodes(self, *args, **kwargs) -> Any: ...
    def neighbors(self, *args, **kwargs) -> Any: ...
    def node_indexes(self, *args, **kwargs) -> Any: ...
    def nodes(self, *args, **kwargs) -> Any: ...
    def num_edges(self, *args, **kwargs) -> Any: ...
    def num_nodes(self, *args, **kwargs) -> Any: ...
    def out_degree(self, *args, **kwargs) -> Any: ...
    def out_edges(self, *args, **kwargs) -> Any: ...
    def predecessor_indices(self, *args, **kwargs) -> Any: ...
    def predecessors(self, *args, **kwargs) -> Any: ...
    def read_edge_list(self, *args, **kwargs) -> Any: ...
    def remove_edge(self, *args, **kwargs) -> Any: ...
    def remove_edge_from_index(self, *args, **kwargs) -> Any: ...
    def remove_edges_from(self, *args, **kwargs) -> Any: ...
    def remove_node(self, *args, **kwargs) -> Any: ...
    def remove_node_retain_edges(self, *args, **kwargs) -> Any: ...
    def remove_nodes_from(self, *args, **kwargs) -> Any: ...
    def subgraph(self, *args, **kwargs) -> Any: ...
    def substitute_node_with_subgraph(self, *args, **kwargs) -> Any: ...
    def successor_indices(self, *args, **kwargs) -> Any: ...
    def successors(self, *args, **kwargs) -> Any: ...
    def to_dot(lambdanode) -> Any: ...
    def to_undirected(self, *args, **kwargs) -> Any: ...
    def update_edge(self, *args, **kwargs) -> Any: ...
    def update_edge_by_index(self, *args, **kwargs) -> Any: ...
    def weighted_edge_list(self, *args, **kwargs) -> Any: ...
    def write_edge_list(self, *args, **kwargs) -> Any: ...
    def __delitem__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __getstate__(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class PyGraph:
    multigraph: ClassVar[Any] = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def add_edge(self, *args, **kwargs) -> Any: ...
    def add_edges_from(self, *args, **kwargs) -> Any: ...
    def add_edges_from_no_data(self, *args, **kwargs) -> Any: ...
    def add_node(self, *args, **kwargs) -> Any: ...
    def add_nodes_from(self, *args, **kwargs) -> Any: ...
    def adj(self, *args, **kwargs) -> Any: ...
    def compose(other_graph, node_map) -> Any: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def degree(self, *args, **kwargs) -> Any: ...
    def edge_index_map(self, *args, **kwargs) -> Any: ...
    def edge_indices(self, *args, **kwargs) -> Any: ...
    def edge_list(self, *args, **kwargs) -> Any: ...
    def edges(self, *args, **kwargs) -> Any: ...
    def extend_from_edge_list(self, *args, **kwargs) -> Any: ...
    def extend_from_weighted_edge_list(self, *args, **kwargs) -> Any: ...
    def from_adjacency_matrix(self, *args, **kwargs) -> Any: ...
    def get_all_edge_data(self, *args, **kwargs) -> Any: ...
    def get_edge_data(self, *args, **kwargs) -> Any: ...
    def get_node_data(self, *args, **kwargs) -> Any: ...
    def has_edge(self, *args, **kwargs) -> Any: ...
    def neighbors(self, *args, **kwargs) -> Any: ...
    def node_indexes(self, *args, **kwargs) -> Any: ...
    def nodes(self, *args, **kwargs) -> Any: ...
    def num_edges(self, *args, **kwargs) -> Any: ...
    def num_nodes(self, *args, **kwargs) -> Any: ...
    def read_edge_list(self, *args, **kwargs) -> Any: ...
    def remove_edge(self, *args, **kwargs) -> Any: ...
    def remove_edge_from_index(self, *args, **kwargs) -> Any: ...
    def remove_edges_from(self, *args, **kwargs) -> Any: ...
    def remove_node(self, *args, **kwargs) -> Any: ...
    def remove_nodes_from(self, *args, **kwargs) -> Any: ...
    def subgraph(self, *args, **kwargs) -> Any: ...
    def to_dot(lambdanode) -> Any: ...
    def update_edge(self, *args, **kwargs) -> Any: ...
    def update_edge_by_index(self, *args, **kwargs) -> Any: ...
    def weighted_edge_list(self, *args, **kwargs) -> Any: ...
    def write_edge_list(self, *args, **kwargs) -> Any: ...
    def __delitem__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __getstate__(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def ancestors(*args, **kwargs) -> Any: ...
def bfs_successors(*args, **kwargs) -> Any: ...
def collect_runs(*args, **kwargs) -> Any: ...
def cycle_basis(*args, **kwargs) -> Any: ...
def dag_longest_path(*args, **kwargs) -> Any: ...
def dag_longest_path_length(*args, **kwargs) -> Any: ...
def dag_weighted_longest_path(*args, **kwargs) -> Any: ...
def dag_weighted_longest_path_length(*args, **kwargs) -> Any: ...
def descendants(*args, **kwargs) -> Any: ...
def digraph_adjacency_matrix(*args, **kwargs) -> Any: ...
def digraph_all_pairs_dijkstra_path_lengths(*args, **kwargs) -> Any: ...
def digraph_all_pairs_dijkstra_shortest_paths(*args, **kwargs) -> Any: ...
def digraph_all_simple_paths(*args, **kwargs) -> Any: ...
def digraph_astar_shortest_path(*args, **kwargs) -> Any: ...
def digraph_bipartite_layout(*args, **kwargs) -> Any: ...
def digraph_circular_layout(*args, **kwargs) -> Any: ...
def digraph_complement(*args, **kwargs) -> Any: ...
def digraph_core_number(*args, **kwargs) -> Any: ...
def digraph_dfs_edges(*args, **kwargs) -> Any: ...
def digraph_dijkstra_shortest_path_lengths(*args, **kwargs) -> Any: ...
def digraph_dijkstra_shortest_paths(*args, **kwargs) -> Any: ...
def digraph_distance_matrix(*args, **kwargs) -> Any: ...
def digraph_find_cycle(*args, **kwargs) -> Any: ...
def digraph_floyd_warshall(graph, weight_fn=...) -> Any: ...
def digraph_floyd_warshall_numpy(*args, **kwargs) -> Any: ...
def digraph_is_isomorphic(*args, **kwargs) -> Any: ...
def digraph_is_subgraph_isomorphic(*args, **kwargs) -> Any: ...
def digraph_k_shortest_path_lengths(*args, **kwargs) -> Any: ...
def digraph_num_shortest_paths_unweighted(*args, **kwargs) -> Any: ...
def digraph_random_layout(*args, **kwargs) -> Any: ...
def digraph_shell_layout(*args, **kwargs) -> Any: ...
def digraph_spiral_layout(*args, **kwargs) -> Any: ...
def digraph_spring_layout(*args, **kwargs) -> Any: ...
def digraph_transitivity(*args, **kwargs) -> Any: ...
def digraph_union(*args, **kwargs) -> Any: ...
def directed_gnm_random_graph(*args, **kwargs) -> Any: ...
def directed_gnp_random_graph(*args, **kwargs) -> Any: ...
def graph_adjacency_matrix(graph, weight_fn) -> Any: ...
def graph_all_pairs_dijkstra_path_lengths(*args, **kwargs) -> Any: ...
def graph_all_pairs_dijkstra_shortest_paths(*args, **kwargs) -> Any: ...
def graph_all_simple_paths(*args, **kwargs) -> Any: ...
def graph_astar_shortest_path(*args, **kwargs) -> Any: ...
def graph_bipartite_layout(*args, **kwargs) -> Any: ...
def graph_circular_layout(*args, **kwargs) -> Any: ...
def graph_complement(*args, **kwargs) -> Any: ...
def graph_core_number(*args, **kwargs) -> Any: ...
def graph_dfs_edges(*args, **kwargs) -> Any: ...
def graph_dijkstra_shortest_path_lengths(*args, **kwargs) -> Any: ...
def graph_dijkstra_shortest_paths(*args, **kwargs) -> Any: ...
def graph_distance_matrix(*args, **kwargs) -> Any: ...
def graph_floyd_warshall(graph, weight_fn=...) -> Any: ...
def graph_floyd_warshall_numpy(graph, weight_fn) -> Any: ...
def graph_greedy_color(*args, **kwargs) -> Any: ...
def graph_is_isomorphic(*args, **kwargs) -> Any: ...
def graph_is_subgraph_isomorphic(*args, **kwargs) -> Any: ...
def graph_k_shortest_path_lengths(*args, **kwargs) -> Any: ...
def graph_num_shortest_paths_unweighted(*args, **kwargs) -> Any: ...
def graph_random_layout(*args, **kwargs) -> Any: ...
def graph_shell_layout(*args, **kwargs) -> Any: ...
def graph_spiral_layout(*args, **kwargs) -> Any: ...
def graph_spring_layout(*args, **kwargs) -> Any: ...
def graph_transitivity(*args, **kwargs) -> Any: ...
def is_directed_acyclic_graph(*args, **kwargs) -> Any: ...
def is_matching(*args, **kwargs) -> Any: ...
def is_maximal_matching(*args, **kwargs) -> Any: ...
def is_weakly_connected(*args, **kwargs) -> Any: ...
def layers(*args, **kwargs) -> Any: ...
def lexicographical_topological_sort(*args, **kwargs) -> Any: ...
def max_weight_matching(*args, **kwargs) -> Any: ...
def minimum_spanning_edges(graph, weight_fn) -> Any: ...
def minimum_spanning_tree(graph, weight_fn) -> Any: ...
def number_weakly_connected_components(*args, **kwargs) -> Any: ...
def random_geometric_graph(*args, **kwargs) -> Any: ...
def strongly_connected_components(*args, **kwargs) -> Any: ...
def topological_sort(*args, **kwargs) -> Any: ...
def undirected_gnm_random_graph(*args, **kwargs) -> Any: ...
def undirected_gnp_random_graph(*args, **kwargs) -> Any: ...
def weakly_connected_components(*args, **kwargs) -> Any: ...
