# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This file contains only type annotations for PyO3 functions and classes
# For implementation details, see __init__.py and lib.rs

from typing import Any
from .pygraph import PyGraph
from .pydigraph import PyDiGraph

def binomial_tree_graph(*args, **kwargs) -> Any: ...
def cycle_graph(*args, **kwargs) -> Any: ...
def directed_binomial_tree_graph(*args, **kwargs) -> Any: ...
def directed_cycle_graph(*args, **kwargs) -> Any: ...
def directed_grid_graph(*args, **kwargs) -> Any: ...
def directed_hexagonal_lattice_graph(*args, **kwargs) -> Any: ...
def directed_mesh_graph(*args, **kwargs) -> Any: ...
def directed_path_graph(*args, **kwargs) -> Any: ...
def directed_star_graph(*args, **kwargs) -> Any: ...
def grid_graph(*args, **kwargs) -> Any: ...
def hexagonal_lattice_graph(*args, **kwargs) -> Any: ...
def mesh_graph(*args, **kwargs) -> Any: ...
def path_graph(*args, **kwargs) -> Any: ...
def star_graph(*args, **kwargs) -> Any: ...
