name: Docs Publish
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

concurrency:
  group: docs-gh-pages

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit'
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5  # v2.19.3
      with:
        egress-policy: audit
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install -U --group testinfra
        sudo apt-get install graphviz pandoc
    - name: Build docs
      run: |
        tools/build_documentation_release.sh
    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa  # v3.0.1
      with:
        name: html_docs
        path: release_docs/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: release_docs/
        force_orphan: true
