---
name: Wheel Builds
on:
  push:
    tags:
      - '*'
jobs:
  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    needs: ["build_wheels", "build-win32-wheels"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install deps
        run: pip install -U twine setuptools-rust
      - name: Build sdist
        run: python setup.py sdist bdist_wheel
        env:
          RUSTWORKX_PKG_NAME: retworkx
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*
      - name: Upload to PyPI
        run: twine upload ./dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: retworkx-ci
